#-------------------------------
# General Site Settings

title: Tech UpNext - Serving Tech Updates
description: Tech UpNext was found in 2018 with the aim of serving you the latest and upcoming technologies, gadgets with features, games, how to and many more. Subscribe us to get updates! # this means to ignore newlines until "baseurl:"
baseurl: "/techupnext" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com


#-------------------------------
# About Section
author-name:   Deepak L. Karna
author-avatar: author.png


#-------------------------------
# Contact links
facebook:  https://facebook.com/techupnext # Add your Facebook handle
twitter:   https://twitter.com/tech_upnext # Add your Twitter handle
instagram: https://www.instagram.com/ # Add your LinkedIn handle
pinterest: https://www.pinterest.com/ # Add your Facebook handle


#-------------------------------
# Comment Section (Disqus)
disqus-identifier: mr-brown # Add your shortname for Disqus Comment. For example mr-brown


#-------------------------------
# Instagram Feed
instafeed: true # To enable the instafeed, use the value true. To turn off use the value false.


#-------------------------------
# Google Analytics
google-analytics: # Add your identifier. For example UA-99631805-1.


#-------------------------------
# Newsletter
mailchimp: # Add your MailChimp form identifier. For example - blogenjoyfreedom.us16.list-manage.com/subscribe/post?u=cd56155d76ddeeb4c0bc4d080&amp;id=7a526cd13e


#-------------------------------
# Build settings
markdown: kramdown
permalink: ':title/'
plugins:
  - jekyll-paginate
  - jekyll-sitemap

paginate: 7
paginate_path: "/page/:num"

include:
  - _pages

sass:
  sass_dir: _sass
  style: compressed


#-------------------------------
# Exclude from processing.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
